version: "3"
services:
  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html/
    networks:
      - internal
  php:
    image: php:fpm-alpine
    container_name: php-fpm
    volumes:
      - ./www:/var/www/html/
    networks:
      - internal
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: case
    volumes:
      - ./db:/docker-entrypoint-initdb.d1
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  internal:
    driver: bridge